//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONG
    {
        public int ID { get; set; }
        public int ID_NhanVien { get; set; }
        public Nullable<System.DateTime> LuongThang { get; set; }
        public Nullable<double> TongOT { get; set; }
        public Nullable<decimal> TongKhauTru { get; set; }
        public Nullable<decimal> PIT { get; set; }
        public Nullable<decimal> ThucNhan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
