//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULA_OF_PAYROLL
    {
        public int ID { get; set; }
        public string Type_Of_Salary { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string Formula { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
