//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_RESET_DAY_OF_TAKE_LEAVE
    {
        public int ID { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<System.DateTime> ThangNam { get; set; }
        public Nullable<int> ID_LoaiNgayNghi { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
