//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAUTRULUONG
    {
        public int ID { get; set; }
        public System.DateTime ThangNam { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> ThueTNCN { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
