//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_GIOCONG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayGioKetThuc { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<System.DateTime> NgayGioBatDau { get; set; }
        public Nullable<int> ID_GioCong { get; set; }
    
        public virtual LOAI_GIO_CONG LOAI_GIO_CONG { get; set; }
        public virtual NHANSU NHANSU { get; set; }
    }
}
