//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_PHUCAP
    {
        public int ID { get; set; }
        public int ID_NhanVien { get; set; }
        public int ID_PhuCap { get; set; }
        public Nullable<System.DateTime> ThangNam { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
        public virtual PHUCAP PHUCAP { get; set; }
    }
}
